import userApi from './modules/user.uts';
import deviceApi from './modules/device.uts';
import programApi from './modules/program.uts';
import { APIS, BASE_URL } from './config.uts';
import * as types from './types.uts';

export { APIS, BASE_URL };
export { userApi, deviceApi, programApi };
export * from './types.uts';

export default {
  user: userApi,
  device: deviceApi,
  program: programApi
};
